services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=False # Single User mode 
      - WEBUI_NAME=Chatbot Knowledge Base
      - OPENAI_API_BASE_URL=http://model-runner.docker.internal/engines/v1
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - docker-model-runner-mistral
      - docker-model-runner-smoll

  docker-model-runner-mistral:
    provider:
      type: model
      options:
        model: ai/mistral

  docker-model-runner-smoll:
    provider:
      type: model
      options:
        model: ai/smollm2

  mcpo:
    build:
      context: ./mcpo
    container_name: mcpo
    ports:
      - "8000:8000"
    volumes:
      - ./mcpo/config.json:/app/config/config.json:ro
      - ./servers:/app/servers:ro
    restart: unless-stopped

  mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}

volumes:
  open-webui:
  mongodb: